# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/go4/analysis_new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/go4/analysis_new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/go4/analysis_new/CMakeFiles /home/daniel/go4/analysis_new//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/go4/analysis_new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Go4UserAnalysis

# Build rule for target.
Go4UserAnalysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Go4UserAnalysis
.PHONY : Go4UserAnalysis

# fast build rule for target.
Go4UserAnalysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/build
.PHONY : Go4UserAnalysis/fast

#=============================================================================
# Target rules for targets named G__Go4UserAnalysis

# Build rule for target.
G__Go4UserAnalysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 G__Go4UserAnalysis
.PHONY : G__Go4UserAnalysis

# fast build rule for target.
G__Go4UserAnalysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/G__Go4UserAnalysis.dir/build.make CMakeFiles/G__Go4UserAnalysis.dir/build
.PHONY : G__Go4UserAnalysis/fast

G__Go4UserAnalysis.o: G__Go4UserAnalysis.cxx.o
.PHONY : G__Go4UserAnalysis.o

# target to build an object file
G__Go4UserAnalysis.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/G__Go4UserAnalysis.dir/build.make CMakeFiles/G__Go4UserAnalysis.dir/G__Go4UserAnalysis.cxx.o
.PHONY : G__Go4UserAnalysis.cxx.o

G__Go4UserAnalysis.i: G__Go4UserAnalysis.cxx.i
.PHONY : G__Go4UserAnalysis.i

# target to preprocess a source file
G__Go4UserAnalysis.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/G__Go4UserAnalysis.dir/build.make CMakeFiles/G__Go4UserAnalysis.dir/G__Go4UserAnalysis.cxx.i
.PHONY : G__Go4UserAnalysis.cxx.i

G__Go4UserAnalysis.s: G__Go4UserAnalysis.cxx.s
.PHONY : G__Go4UserAnalysis.s

# target to generate assembly for a file
G__Go4UserAnalysis.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/G__Go4UserAnalysis.dir/build.make CMakeFiles/G__Go4UserAnalysis.dir/G__Go4UserAnalysis.cxx.s
.PHONY : G__Go4UserAnalysis.cxx.s

TCronoACQAnalysis.o: TCronoACQAnalysis.cxx.o
.PHONY : TCronoACQAnalysis.o

# target to build an object file
TCronoACQAnalysis.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnalysis.cxx.o
.PHONY : TCronoACQAnalysis.cxx.o

TCronoACQAnalysis.i: TCronoACQAnalysis.cxx.i
.PHONY : TCronoACQAnalysis.i

# target to preprocess a source file
TCronoACQAnalysis.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnalysis.cxx.i
.PHONY : TCronoACQAnalysis.cxx.i

TCronoACQAnalysis.s: TCronoACQAnalysis.cxx.s
.PHONY : TCronoACQAnalysis.s

# target to generate assembly for a file
TCronoACQAnalysis.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnalysis.cxx.s
.PHONY : TCronoACQAnalysis.cxx.s

TCronoACQAnlEvent.o: TCronoACQAnlEvent.cxx.o
.PHONY : TCronoACQAnlEvent.o

# target to build an object file
TCronoACQAnlEvent.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlEvent.cxx.o
.PHONY : TCronoACQAnlEvent.cxx.o

TCronoACQAnlEvent.i: TCronoACQAnlEvent.cxx.i
.PHONY : TCronoACQAnlEvent.i

# target to preprocess a source file
TCronoACQAnlEvent.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlEvent.cxx.i
.PHONY : TCronoACQAnlEvent.cxx.i

TCronoACQAnlEvent.s: TCronoACQAnlEvent.cxx.s
.PHONY : TCronoACQAnlEvent.s

# target to generate assembly for a file
TCronoACQAnlEvent.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlEvent.cxx.s
.PHONY : TCronoACQAnlEvent.cxx.s

TCronoACQAnlProc.o: TCronoACQAnlProc.cxx.o
.PHONY : TCronoACQAnlProc.o

# target to build an object file
TCronoACQAnlProc.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlProc.cxx.o
.PHONY : TCronoACQAnlProc.cxx.o

TCronoACQAnlProc.i: TCronoACQAnlProc.cxx.i
.PHONY : TCronoACQAnlProc.i

# target to preprocess a source file
TCronoACQAnlProc.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlProc.cxx.i
.PHONY : TCronoACQAnlProc.cxx.i

TCronoACQAnlProc.s: TCronoACQAnlProc.cxx.s
.PHONY : TCronoACQAnlProc.s

# target to generate assembly for a file
TCronoACQAnlProc.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQAnlProc.cxx.s
.PHONY : TCronoACQAnlProc.cxx.s

TCronoACQCorrPar.o: TCronoACQCorrPar.cxx.o
.PHONY : TCronoACQCorrPar.o

# target to build an object file
TCronoACQCorrPar.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQCorrPar.cxx.o
.PHONY : TCronoACQCorrPar.cxx.o

TCronoACQCorrPar.i: TCronoACQCorrPar.cxx.i
.PHONY : TCronoACQCorrPar.i

# target to preprocess a source file
TCronoACQCorrPar.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQCorrPar.cxx.i
.PHONY : TCronoACQCorrPar.cxx.i

TCronoACQCorrPar.s: TCronoACQCorrPar.cxx.s
.PHONY : TCronoACQCorrPar.s

# target to generate assembly for a file
TCronoACQCorrPar.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQCorrPar.cxx.s
.PHONY : TCronoACQCorrPar.cxx.s

TCronoACQEventSource.o: TCronoACQEventSource.cxx.o
.PHONY : TCronoACQEventSource.o

# target to build an object file
TCronoACQEventSource.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQEventSource.cxx.o
.PHONY : TCronoACQEventSource.cxx.o

TCronoACQEventSource.i: TCronoACQEventSource.cxx.i
.PHONY : TCronoACQEventSource.i

# target to preprocess a source file
TCronoACQEventSource.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQEventSource.cxx.i
.PHONY : TCronoACQEventSource.cxx.i

TCronoACQEventSource.s: TCronoACQEventSource.cxx.s
.PHONY : TCronoACQEventSource.s

# target to generate assembly for a file
TCronoACQEventSource.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQEventSource.cxx.s
.PHONY : TCronoACQEventSource.cxx.s

TCronoACQMomCalcPar.o: TCronoACQMomCalcPar.cxx.o
.PHONY : TCronoACQMomCalcPar.o

# target to build an object file
TCronoACQMomCalcPar.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCalcPar.cxx.o
.PHONY : TCronoACQMomCalcPar.cxx.o

TCronoACQMomCalcPar.i: TCronoACQMomCalcPar.cxx.i
.PHONY : TCronoACQMomCalcPar.i

# target to preprocess a source file
TCronoACQMomCalcPar.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCalcPar.cxx.i
.PHONY : TCronoACQMomCalcPar.cxx.i

TCronoACQMomCalcPar.s: TCronoACQMomCalcPar.cxx.s
.PHONY : TCronoACQMomCalcPar.s

# target to generate assembly for a file
TCronoACQMomCalcPar.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCalcPar.cxx.s
.PHONY : TCronoACQMomCalcPar.cxx.s

TCronoACQMomCorrPar.o: TCronoACQMomCorrPar.cxx.o
.PHONY : TCronoACQMomCorrPar.o

# target to build an object file
TCronoACQMomCorrPar.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCorrPar.cxx.o
.PHONY : TCronoACQMomCorrPar.cxx.o

TCronoACQMomCorrPar.i: TCronoACQMomCorrPar.cxx.i
.PHONY : TCronoACQMomCorrPar.i

# target to preprocess a source file
TCronoACQMomCorrPar.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCorrPar.cxx.i
.PHONY : TCronoACQMomCorrPar.cxx.i

TCronoACQMomCorrPar.s: TCronoACQMomCorrPar.cxx.s
.PHONY : TCronoACQMomCorrPar.s

# target to generate assembly for a file
TCronoACQMomCorrPar.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQMomCorrPar.cxx.s
.PHONY : TCronoACQMomCorrPar.cxx.s

TCronoACQRawEvent.o: TCronoACQRawEvent.cxx.o
.PHONY : TCronoACQRawEvent.o

# target to build an object file
TCronoACQRawEvent.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawEvent.cxx.o
.PHONY : TCronoACQRawEvent.cxx.o

TCronoACQRawEvent.i: TCronoACQRawEvent.cxx.i
.PHONY : TCronoACQRawEvent.i

# target to preprocess a source file
TCronoACQRawEvent.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawEvent.cxx.i
.PHONY : TCronoACQRawEvent.cxx.i

TCronoACQRawEvent.s: TCronoACQRawEvent.cxx.s
.PHONY : TCronoACQRawEvent.s

# target to generate assembly for a file
TCronoACQRawEvent.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawEvent.cxx.s
.PHONY : TCronoACQRawEvent.cxx.s

TCronoACQRawPar.o: TCronoACQRawPar.cxx.o
.PHONY : TCronoACQRawPar.o

# target to build an object file
TCronoACQRawPar.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawPar.cxx.o
.PHONY : TCronoACQRawPar.cxx.o

TCronoACQRawPar.i: TCronoACQRawPar.cxx.i
.PHONY : TCronoACQRawPar.i

# target to preprocess a source file
TCronoACQRawPar.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawPar.cxx.i
.PHONY : TCronoACQRawPar.cxx.i

TCronoACQRawPar.s: TCronoACQRawPar.cxx.s
.PHONY : TCronoACQRawPar.s

# target to generate assembly for a file
TCronoACQRawPar.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQRawPar.cxx.s
.PHONY : TCronoACQRawPar.cxx.s

TCronoACQUnpackEvent.o: TCronoACQUnpackEvent.cxx.o
.PHONY : TCronoACQUnpackEvent.o

# target to build an object file
TCronoACQUnpackEvent.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackEvent.cxx.o
.PHONY : TCronoACQUnpackEvent.cxx.o

TCronoACQUnpackEvent.i: TCronoACQUnpackEvent.cxx.i
.PHONY : TCronoACQUnpackEvent.i

# target to preprocess a source file
TCronoACQUnpackEvent.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackEvent.cxx.i
.PHONY : TCronoACQUnpackEvent.cxx.i

TCronoACQUnpackEvent.s: TCronoACQUnpackEvent.cxx.s
.PHONY : TCronoACQUnpackEvent.s

# target to generate assembly for a file
TCronoACQUnpackEvent.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackEvent.cxx.s
.PHONY : TCronoACQUnpackEvent.cxx.s

TCronoACQUnpackProc.o: TCronoACQUnpackProc.cxx.o
.PHONY : TCronoACQUnpackProc.o

# target to build an object file
TCronoACQUnpackProc.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackProc.cxx.o
.PHONY : TCronoACQUnpackProc.cxx.o

TCronoACQUnpackProc.i: TCronoACQUnpackProc.cxx.i
.PHONY : TCronoACQUnpackProc.i

# target to preprocess a source file
TCronoACQUnpackProc.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackProc.cxx.i
.PHONY : TCronoACQUnpackProc.cxx.i

TCronoACQUnpackProc.s: TCronoACQUnpackProc.cxx.s
.PHONY : TCronoACQUnpackProc.s

# target to generate assembly for a file
TCronoACQUnpackProc.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Go4UserAnalysis.dir/build.make CMakeFiles/Go4UserAnalysis.dir/TCronoACQUnpackProc.cxx.s
.PHONY : TCronoACQUnpackProc.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... G__Go4UserAnalysis"
	@echo "... Go4UserAnalysis"
	@echo "... G__Go4UserAnalysis.o"
	@echo "... G__Go4UserAnalysis.i"
	@echo "... G__Go4UserAnalysis.s"
	@echo "... TCronoACQAnalysis.o"
	@echo "... TCronoACQAnalysis.i"
	@echo "... TCronoACQAnalysis.s"
	@echo "... TCronoACQAnlEvent.o"
	@echo "... TCronoACQAnlEvent.i"
	@echo "... TCronoACQAnlEvent.s"
	@echo "... TCronoACQAnlProc.o"
	@echo "... TCronoACQAnlProc.i"
	@echo "... TCronoACQAnlProc.s"
	@echo "... TCronoACQCorrPar.o"
	@echo "... TCronoACQCorrPar.i"
	@echo "... TCronoACQCorrPar.s"
	@echo "... TCronoACQEventSource.o"
	@echo "... TCronoACQEventSource.i"
	@echo "... TCronoACQEventSource.s"
	@echo "... TCronoACQMomCalcPar.o"
	@echo "... TCronoACQMomCalcPar.i"
	@echo "... TCronoACQMomCalcPar.s"
	@echo "... TCronoACQMomCorrPar.o"
	@echo "... TCronoACQMomCorrPar.i"
	@echo "... TCronoACQMomCorrPar.s"
	@echo "... TCronoACQRawEvent.o"
	@echo "... TCronoACQRawEvent.i"
	@echo "... TCronoACQRawEvent.s"
	@echo "... TCronoACQRawPar.o"
	@echo "... TCronoACQRawPar.i"
	@echo "... TCronoACQRawPar.s"
	@echo "... TCronoACQUnpackEvent.o"
	@echo "... TCronoACQUnpackEvent.i"
	@echo "... TCronoACQUnpackEvent.s"
	@echo "... TCronoACQUnpackProc.o"
	@echo "... TCronoACQUnpackProc.i"
	@echo "... TCronoACQUnpackProc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

